### PR TITLE
update board manager according to latest head 1a0c55c5e2ec80a6f1fa861…

### PR DESCRIPTION
**Pull request by amitesh-singh**
…ccfced8607dfdfca4

### CODE REVIEW

**Comment by ccjoeg** [comment]
In the future always increment the revision on files that change like:
    cortex-m0plus-1.0.1.tar.bz2 -> cortex-m0plus-1.0.2.tar.bz2

Thanks,
Joe

**Comment by amitesh-singh** [comment]
and update the "version": "1.0.1", entry to 1.0.2 in json as well?

**Comment by ccjoeg** [comment]
Yes

**Comment by amitesh-singh** [comment]
I was wondering if you can provide  repo tag for the release instead.
I think its better to release the firmware code via tag or branch.  I picked the latest HEAD though but it did not feel right. whats do you say?

**Comment by ccjoeg** [comment]
Most everyone else seems to do it with the format that Arduino uses for IDE
releases. A repo tag makes sense but we should probably stick with what
Arduino is doing.

Here is a list of other boards you can use for examples:

https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls

Thanks,
Joe

**Comment by amitesh-singh** [comment]
hrm,

i think you misunderstood me.

I meant about tagging the release for each major release for https://github.com/Engimusing/engimusing-firmware

I was suggesting following steps:
1. In engimusing-firmware repo, for release 1.0.2, you create either a tag or branch named 
1.0.2
2. I pick that branch for creating the pkg and add into board manager.
3. In case of some issues, Fix the bugs in master of  engimusing-firmware repo and then cherry-pick this to 1.0.2 and then repeat 2 (for me)

I think in this way we could track/log every release.

**Comment by ccjoeg** [comment]
Yes, that makes sense.

**Pull request merged**
